### PR TITLE
Change dict/seq checks to use collections ABCs (for duck-typed params)

### PR DESCRIPTION
**Pull request by bkeroack**
This allows parameters that provide sufficient interface to be used as dictionaries or sequence types (list/tuple) to pass the respective checks.

### CODE REVIEW

**Comment by bkeroack** [comment]
Update: I changed my mind, I think duck-typed lists and dicts should have a separate predicate so I've implemented those.

- issequence (allows duck-typed lists)
- ismapping (allows duck-typed dicts)
- mapping_of (allows duck-typed dicts with predicates about keys/values like dict_of)
- tests and documentation for above

Let me know what you think please.

**Comment by prechelt** [comment]
Hi Benjamen,

I am all in favor of supporting the Sequence and Mapping ABCs.
In fact I had tried to do it but then refrained (due to my lack of experience with advanced 'import' logic) when I saw that they had been moved from collections to collections.abc in Python 3.3. I think I have overlooked that they are still in collections, too.
So let's go for them.

However, I would also like to keep the API small.

With your current additions, we would now be at 15 different builtin predicates. Too many for my taste.
But given the pragmatic spirit of the current set of predicates, I think there is a leaner approach that still gets us all we want. As follows:
- Make list_of() test for collections.MutableSequence instead of list.
- Kick out tuple_of(), because in that same spirit it would be the same as sequence_of(). (Yeah! That's why the module is still called beta: There was _something_ about tuple_of() I did not quite like. I don't think we will break much code and even if we do, it is very easy to fix.)
- Kick out issequence() because this is the same as simply annotating collections.Sequence.
- Make dict_of() test for collections.Mapping instead of dict. (That is, kick out dict_of() and rename mapping_of() to dict_of().)
- Kick out ismapping() because it is the same as simply annotating collections.Mapping.
- And what do you think about using the shorter name seq_of() instead of sequence_of()? I am in favor of it.

This makes all parts of the module shorter (README.md, the code, the tests), yet functionally retains essentially everything of what you suggested.

**Comment by bkeroack** [comment]
I agree with all your bullet points, with one caveat:

- seq_of() will (perhaps suprisingly) allow strings since they satisfy collections.Sequence. For example seq_of(str) is essentially identical to a plain str predicate since the subelements (chars) are also string objects (see image below). I've tried to make it clear in the documentation to use list_of() instead of seq_of() if only true lists of strings should be allowed.

Otherwise all the suggestions have been implemented.

image

**Comment by bkeroack** [comment]
Hi Lutz,

Not sure if you get notifications from Github but I've implemented your
suggestions in the original pull request.

Cheers,
Ben

**Comment by prechelt** [comment]
Benjamen,

 

yes, I get those notifications.

I am a bit loaded in the moment but will see to it soon.

May take a few days, though.

Sorry,

 

  Lutz

**Comment by prechelt** [comment]
Benjamen,

what a mess!

When you contacted me, I had totally forgotten that there were 5 more commits (of June 2014) in my local repo that I had not yet pushed to github. Bad idea.

It turns out that, in our dialog, we have reinvented a lot of things that were in fact already there.
When I tried to merge your changes, I got extremely confused by the collisions.
I ended up not using your commits directly but rather adding the remaining changes to my own last master commit manually: 
- using collections.X rather than collections.abc.X, 
- the PyPy test fixes, 
- the tc.seq_of(str) special case (which will now _not_ accept a plain string).

There are various other tweaks compared to the v0.3b state you have seen and I am now willing to call this v1.0 as soon as you tell me that
- the tests indeed work with PyPy now and
- you are happy with the shape and details of the API overall.

Note that you will now need pytest to run the tests.

**Pull request closed without merging**
